# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Cell-Segmentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://cellsegmentationyolov8.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ecfb45ac7a344b6e8881e1d9fdd4ff10 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fe21253a4c3d442c9c3621d1e22b298d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cellsegmentationyolov8.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ecfb45ac7a344b6e8881e1d9fdd4ff10 }}/cell:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Cell-Segmentation'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b96052dba9ce4ad9b03d3e27d516dc25 }}
        images: 'cellsegmentationyolov8.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ecfb45ac7a344b6e8881e1d9fdd4ff10 }}/cell:${{ github.sha }}'